#########################
# DO NOT EDIT THIS FILE #
#########################

from GenericBot import GenericBot_client
from main import get_token, get_db_method, add_features

Bot = GenericBot_client(get_token(), get_db_method())
add_features(Bot)
Bot.activate()